services:
  - type: web
    name: gpacademy-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: MYSQL_PUBLIC_URL
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: gpacademy-web
    runtime: node
    rootDir: frontend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://gpacademy-nqca.onrender.com
      - key: PORT
        value: 3000
